### ISSUE TITLE
Typo In Basket.java file

### ISSUE THREAD

**Issue by JavaBaz** [farzadafi/cinema_96#4]
I came across a small typo in the code of the Basket class within the org.cinema package. The variable 'filmNam' in the class should be 'filmName'. This typo might cause confusion and hinder the readability of the code.

Current code snippet:
``` java
public class Basket {
    .
    .
    private String filmNam;
    .
    .
    .
```

Proposed fix:
To resolve this issue, the typo should be corrected by replacing 'filmNam' with 'filmName' on line 6 of the code snippet. The corrected code should look like this:
``` java
public class Basket {
    .
    .
    private String filmName;
    .
    .
    .
```
This simple fix will ensure that the variable name is consistent and accurately reflects its intended purpose, enhancing the code's clarity and maintainability.

Thank you for your attention to this matter. Let me know if you need any further assistance!

**Comment by farzadafi** [comment]
This is an excellent attention message for friends, Thanks, Heart :)
