### ISSUE TITLE
Refactoring Opportunity: Consolidate Similar Methods in BaseRepository using Generics

### ISSUE THREAD

**Issue by JavaBaz** [farzadafi/cinema_96#5]
I noticed that the codebase contains four classes named TicketRepository, CinemaRepository, UserRepository, and AdminRepository, which all appear to have similar methods. This repetition violates the "Don't Repeat Yourself" (DRY) principle in programming, which encourages code reuse and maintainability.

To address this issue, I propose refactoring the code by creating a BaseRepository class that incorporates the common functionality of these four classes. By utilizing generics, we can achieve a more concise and modular design.

Here's a brief overview of how the refactored code structure could look:

1. Create a BaseRepository<T> class:
``` Java
public abstract class BaseRepository<T> {
    // Define common methods and functionality here
}
```

2. Modify the existing repository classes to extend BaseRepository and specify the appropriate generic type:

``` Java
public class TicketRepository extends BaseRepository<Ticket> {
    // Implement specific methods related to Ticket operations
}

public class CinemaRepository extends BaseRepository<Cinema> {
    // Implement specific methods related to Cinema operations
}

public class UserRepository extends BaseRepository<User> {
    // Implement specific methods related to User operations
}

public class AdminRepository extends BaseRepository<Admin> {
    // Implement specific methods related to Admin operations
}

```

By implementing this refactoring, we can eliminate code duplication and enhance the maintainability of the system. Additionally, any changes or improvements made in the BaseRepository class will automatically propagate to all the subclasses, reducing the risk of inconsistencies and bugs.

Applying the DRY principle in this scenario will improve code readability, reduce potential errors, and make future modifications or additions to the repository functionality more efficient.

Let me know if you need further clarification or assistance. Happy coding! 🥳

**Comment by farzadafi** [comment]
Thanks for you :)
 Tractor :)
   :)))

**Comment by JavaBaz** [comment]
😄🙏❤️
